language: node_js

node_js:
  - "12"
  - "10"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8

before_script:
  - yarn install

script:
  - yarn run test:serve

cache:
  yarn: true
  directories:
    - node_modules
